import type { Experience } from "./types"

export const experiences: Experience[] = [
  {
    company: "AIBOS Uganda",
    role: "DevSecOps Engineer",
    period: "Feb 2024 – Present",
    type: "Full-time",
    borderColor: "border-l-amber-500",
    bullets: [
      "Own CI/CD posture on GitHub Actions, cutting deploy time ~60% while adding SBOM generation, container scanning, and signature verification",
      "Run infrastructure-as-code (Terraform) across AWS, Azure, and GCP with policy-as-code gates on every plan",
      "Harden Kubernetes workloads with Pod Security Standards, NetworkPolicies, and supply-chain controls (cosign / Trivy)",
      "Wire Prometheus + Grafana + Loki dashboards with SLO-driven alerts and on-call runbooks",
      "Drive compliance posture (encryption, RBAC, secrets via Vault) across the cloud estate",
    ],
    tags: [
      "GitHub Actions",
      "Terraform",
      "Kubernetes",
      "Trivy",
      "Cosign",
      "Vault",
      "Prometheus",
      "Grafana",
      "AWS",
    ],
  },
  {
    company: "Sauti Health",
    role: "Developer · Engineering Partner",
    period: "2026 – Present",
    type: "Contract",
    borderColor: "border-l-rose-500",
    bullets: [
      "Partner with the Sauti Health team on the engineering behind a pre-hospital emergency dispatch platform for sub-Saharan Africa",
      "Build and harden backend services that coordinate community responders and motorcycle riders over USSD on basic 2G phones",
      "Ship offline-first responder workflows on low-end Android, with sync, retries, and conflict resolution for patchy networks",
      "Integrate mobile-money payment flows (MTN MoMo · Airtel Money) and DHIS2 reporting for health-system interoperability",
      "Instrument telemetry, dashboards, and CI gates on safety-critical paths so dispatch reliability stays measurable",
    ],
    tags: [
      "Python",
      "FastAPI",
      "PostgreSQL",
      "USSD/IVR",
      "Mobile Money",
      "DHIS2",
      "Offline-first",
      "Observability",
    ],
  },
  {
    company: "Ionatec · Iona Institute of Technology",
    role: "Co-founder · ML & Agentic Engineer",
    period: "Feb 2023 – Present",
    type: "Part-time",
    borderColor: "border-l-primary",
    bullets: [
      "Co-founded Ionatec (ionatec.com) — an engineering institute and applied-AI studio training East African engineers on real production stacks",
      "Ship LLM agents on the Claude Agent SDK + LangGraph: tool-use, retrieval, multi-agent orchestration, and evals",
      "Build RAG pipelines on Qdrant / pgvector with hybrid retrieval, rerank, and Braintrust/Promptfoo eval harnesses",
      "Deliver classical ML for classification, regression, and ranking — with monitoring, drift detection, and retraining loops",
      "Run the engineering curriculum and mentor residents from prototype through production",
    ],
    tags: [
      "Claude Agent SDK",
      "LangGraph",
      "MCP",
      "Qdrant",
      "Braintrust",
      "Python",
      "FastAPI",
      "Next.js",
      "scikit-learn",
    ],
  },
  {
    company: "Makerere University",
    role: "Student Software Engineer",
    period: "Jan 2022 – Present",
    type: "Part-time",
    borderColor: "border-l-green-500",
    bullets: [
      "Built TaskApp — a Kotlin task management app with real-time Firebase sync",
      "Developed scalable cross-platform apps using React Native and Flutter",
      "Implemented secure JWT and biometric authentication flows",
      "Delivered a fintech mobile app with digital payments, rewards, and transaction tracking",
      "Integrated third-party payment APIs and designed scalable backend architecture",
    ],
    tags: ["Kotlin", "React Native", "Flutter", "Firebase", "JWT", "Fintech"],
  },
  {
    company: "PAHAPPA LIMITED",
    role: "DevOps Intern → Engineer",
    period: "Jun 2022 – Jan 2024",
    type: "Full-time",
    borderColor: "border-l-orange-500",
    bullets: [
      "Built enterprise applications with Spring Boot (MVC, Data JPA, Security, Cloud)",
      "Used Hibernate ORM/JPA with MySQL, PostgreSQL, Oracle, and MongoDB databases",
      "Designed Microservice and Monolithic architectures based on project requirements",
      "Developed RESTful APIs and event-driven systems for high-throughput workflows",
    ],
    tags: [
      "Spring Boot",
      "Java",
      "Hibernate",
      "MySQL",
      "PostgreSQL",
      "Microservices",
      "REST API",
    ],
  },
  {
    company: "WEB INFO-NET LIMITED",
    role: "Application Developer Intern & Trainer",
    period: "Jun 2018 – Aug 2022",
    type: "Internship",
    borderColor: "border-l-pink-500",
    bullets: [
      "Developed mobile apps using Swift, Java, and Kotlin for iOS and Android platforms",
      "Built an Odoo-based Employment Management System for HR automation",
      "Implemented secure authentication and third-party API integrations",
      "Provided Level 1 technical support, troubleshooting, and end-user training",
    ],
    tags: ["Swift", "Java", "Kotlin", "Odoo", "iOS", "Android"],
  },
  {
    company: "ZALONIDENTALHUB",
    role: "Leading Developer & Maintainer",
    period: "Apr 2022 – Present",
    type: "Contract",
    borderColor: "border-l-teal-500",
    bullets: [
      "Led full SDLC for dental practice management software from conception to delivery",
      "Built C#/VB.NET desktop systems for inventory and patient management",
      "Developed a Flutter mobile app with e-commerce, appointments, and booking features",
      "Ensured seamless desktop-mobile data interoperability",
      "Led a team of developers, defining software architectures and coding standards",
    ],
    tags: ["C#", "VB.NET", "Flutter", "Desktop", "Mobile", "Team Lead"],
  },
]
