import type { Experience } from "./types"

export const experiences: Experience[] = [
  {
    company: "AIBOS Uganda",
    role: "DevOps Engineer",
    period: "Feb 2024 – Present",
    type: "Full-time",
    borderColor: "border-l-blue-500",
    bullets: [
      "Implemented CI/CD pipelines with GitHub Actions, cutting deployment time by 60%",
      "Managed infrastructure as code (IaC) with Terraform across AWS, Azure, and GCP",
      "Orchestrated containerised workloads using Docker, Kubernetes, and AWS ECS",
      "Set up Prometheus/Grafana monitoring dashboards for real-time system observability",
      "Enforced security and compliance policies across cloud infrastructure environments",
    ],
    tags: [
      "GitHub Actions",
      "Terraform",
      "Docker",
      "Kubernetes",
      "AWS",
      "Prometheus",
      "Grafana",
    ],
  },
  {
    company: "IONA Tech",
    role: "AI / ML Engineer",
    period: "Feb 2023 – Present",
    type: "Part-time",
    borderColor: "border-l-purple-500",
    bullets: [
      "Designed and trained ML models for classification, regression, and recommendation tasks",
      "Built end-to-end ML pipelines from data ingestion through to model deployment",
      "Performed data preprocessing and feature engineering with Pandas, NumPy, and scikit-learn",
      "Evaluated and optimised models using cross-validation, hyperparameter tuning, and A/B testing",
      "Implemented model monitoring and logging in production environments",
    ],
    tags: ["Python", "scikit-learn", "Pandas", "NumPy", "TensorFlow", "ML Pipelines"],
  },
  {
    company: "Makerere University",
    role: "Student Software Engineer",
    period: "Jan 2022 – Present",
    type: "Part-time",
    borderColor: "border-l-green-500",
    bullets: [
      "Built TaskApp — a Kotlin task management app with real-time Firebase sync",
      "Developed scalable cross-platform apps using React Native and Flutter",
      "Implemented secure JWT and biometric authentication flows",
      "Delivered a fintech mobile app with digital payments, rewards, and transaction tracking",
      "Integrated third-party payment APIs and designed scalable backend architecture",
    ],
    tags: ["Kotlin", "React Native", "Flutter", "Firebase", "JWT", "Fintech"],
  },
  {
    company: "PAHAPPA LIMITED",
    role: "DevOps Intern → Employee",
    period: "Jun 2022 – Jan 2024",
    type: "Full-time",
    borderColor: "border-l-orange-500",
    bullets: [
      "Built enterprise applications with Spring Boot (MVC, Data JPA, Security, Cloud)",
      "Used Hibernate ORM/JPA with MySQL, PostgreSQL, Oracle, and MongoDB databases",
      "Designed Microservice and Monolithic architectures based on project requirements",
      "Developed RESTful APIs and event-driven systems for high-throughput workflows",
    ],
    tags: [
      "Spring Boot",
      "Java",
      "Hibernate",
      "MySQL",
      "PostgreSQL",
      "Microservices",
      "REST API",
    ],
  },
  {
    company: "WEB INFO-NET LIMITED",
    role: "Application Developer Intern & Trainer",
    period: "Jun 2018 – Aug 2022",
    type: "Internship",
    borderColor: "border-l-pink-500",
    bullets: [
      "Developed mobile apps using Swift, Java, and Kotlin for iOS and Android platforms",
      "Built an Odoo-based Employment Management System for HR automation",
      "Implemented secure authentication and third-party API integrations",
      "Provided Level 1 technical support, troubleshooting, and end-user training",
    ],
    tags: ["Swift", "Java", "Kotlin", "Odoo", "iOS", "Android"],
  },
  {
    company: "ZALONIDENTALHUB",
    role: "Leading Developer & Maintainer",
    period: "Apr 2022 – Present",
    type: "Contract",
    borderColor: "border-l-teal-500",
    bullets: [
      "Led full SDLC for dental practice management software from conception to delivery",
      "Built C#/VB.NET desktop systems for inventory and patient management",
      "Developed a Flutter mobile app with e-commerce, appointments, and booking features",
      "Ensured seamless desktop-mobile data interoperability",
      "Led a team of developers, defining software architectures and coding standards",
    ],
    tags: ["C#", "VB.NET", "Flutter", "Desktop", "Mobile", "Team Lead"],
  },
]
